# Generated by Django 3.2 on 2021-09-21 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='day',
            new_name='date',
        ),
    ]
