# Generated by Django 3.2 on 2021-09-28 05:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_rename_day_record_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='date',
        ),
        migrations.AddField(
            model_name='record',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
